### ISSUE TITLE
Add new list of languages at README

### ISSUE THREAD

**Issue by ppKrauss** [nijel/enca#39]
Important for us, the potential  users! A list of valid languages (`enca -l  languages` )  in the [current  version](https://github.com/nijel/enca/releases), at the [README.md file](https://github.com/nijel/enca/blob/master/README.md).

PS:  UBUNTU is ugly on update, my `enca --version` is 2005 with only few languages... **How to upgrade it on UBUNTU?** (other good link or information for README)

**Comment by nijel** [comment]
The list is AFAIK up to date. There has been really no development here for years.
